version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - db-data:/opt/keycloak/data
    labels:
      org.labels-schema.group: "iam"

volumes:
  db-data: {}